module.exports = {
	"Acacia": "Edible flower",
	"Aloe Vera Flower": "Aloe Vera",
	"Apricot Flower": "Prunus mume",
	"Arabian jasmine, Jasminum Sambac": "Jasminum sambac",
	"Asiatic Lily": "Lilium",
	"Aster": "Aster (genus)",
	"Balsam": "Impatiens",
	"Bleeding Heart": "Lamprocapnos",
	"Blood Lily": "Haemanthus coccineus",
	"Bluebell": "Hyacinthoides",
	"Bluestar": "Amsonia",
	"Butea Monosperma": "Butea monosperma",
	"Canna Flower": "Canna indica",
	"Canna Lily": "Canna (plant)",
	"Castor Ricinus": "Ricinus",
	"Chamomile Vine": "Clitoria ternatea",
	"Cockscomb Flower": "Celosia",
	"Common Lantana": "Lantana camara",
	"Common White Frangipani": "Plumeria",
	"Cone Flower": "Echinacea purpurea",
	"Crape Jasmine": "Tabernaemontana divaricata",
	"Creeper Services": "Campsis radicans",
	"Cypress Vine, Star Glory": "Ipomoea quamoclit",
	"Daisy": "Bellis perennis",
	"Forest Ghost Flower": "Aeginetia indica",
	"Glory Lily": "Gloriosa (plant)",
	"Golden Frangipani": "Plumeria pudica",
	"Golden Shower Flower": "Cassia fistula",
	"Indigo Flower": "Baptisia",
	"Iris": "Iris (plant)",
	"Lady Finger Flower": "Thelymitra crinita",
	"Ladys slipper orchid": "Cypripedioideae",
	"Lotus": "Lotus flower",
	"Marigold": "Tagetes erecta",
	"Mexican Prickly Poppy": "Argemone mexicana",
	"Mexican Tuberose": "Agave amica",
	"Monsoon lily": "Lilium mackliniae",
	"Narcissus": "Narcissus (plant)",
	"Night Blooming Jasmine": "Cestrum nocturnum",
	"Orange Blossom": "Blossom",
	"Orange Tiger Lily": "Lilium bulbiferum",
	"Peacock Flower": "Caesalpinia pulcherrima",
	"Periwinkle": "Catharanthus",
	"Pomegranate Flower": "Catunaregam",
	"Prickly Pear": "Opuntia basilaris",
	"Primrose": "Primulaceae",
	"Purple Passion": "Passiflora edulis",
	"Rosemallows": "Malva",
	"Sandalwood Flower": "Santalum album",
	"Scarlet": "Clematis texensis",
	"Water Lily": "Nymphaeaceae",
	"Zombi Pea, Butterfly Pea": "Vigna vexillata",
};