module.exports = {
	"African Cherry Orange": "African mango",
	"Atis (Annona Squamosa)": "Sugar apple",
	Lime: "Lime fruit",
	Orange: "Orange fruit",
	Plantain: "Plantain fruit",
	Mandarine: "Mandarin orange",
	Cacao: "Theobroma cacao",
	"Grewia asiatica (phalsa or falsa)": "Grewia asiatica",
	Date: "Date palm",
	Currant: "Ribes",
	"Rose apple": "Syzygium aqueum",
	Satsuma: "Citrus unshiu",
	Squash: "Cucurbita",
	"Santol (Cotton Fruit)": "Sandoricum koetjape",
	Kiwifruit: "Actinidia deliciosa",
	Pawpaw: "Asimina",
	Honeydew: "Honeydew (melon)",
	"Macopa (Wax Apple)": "Java apple",
	"Mamey Apple": "Mammea americana",
	"Japanese plum": "Prunus mume",
	Honeyberry: "Lonicera caerulea",
	"Hala Fruit": "Pandanus tectorius",
	"Chico fruit": "Manilkara zapota",
	"Sarguelas (Red Mombin)": "Red Mombin",
	"Tambis (Water Apple)": "Syzygium",
	"Carolina reaper": "Capsicum chinense",
};