module.exports = {
	"Alder": "Alnus glutinosa",
	"Apple": "Malus",
	"Bat Fig": "Ficus amplissima",
	"Bigtooth Aspen": "Aspen",
	"Bitternut Hickory": "Hickory",
	"Black Ash": "Acer negundo",
	"Black Birch": "Birch",
	"Black Cherry": "Prunus serrulata",
	"Black Walnut": "Juglans",
	"Bristlecone Hemlock": "Tsuga",
	"Butternut": "Butternut tree",
	"Common Fig": "Ficus",
	"Common Lime": "Tilia",
	"Copper Beech": "Fagus sylvatica",
	"Cucumber": "Magnolia acuminata",
	"Eastern Hemlock": "Populus fremontii",
	"Elder": "Sambucus nigra",
	"English Oak": "Quercus petraea",
	"Flowering Dogwood": "Cornus",
	"Flowering Gum": "Eucalyptus globulus",
	"Giant Redwood": "Giant Redwoods",
	"Hawthorn": "Crataegus monogyna",
	"Holm Oak": "Quercus ilex",
	"Kumquat": "Acer saccharinum",
	"Monkey Puzzle": "Araucaria araucana",
	"Mountain Magnolia": "Magnolia officinalis",
	"Neem": "Azadirachta",
	"Nootka Cypress": "Cupressus macrocarpa",
	"Patagonian Cypress": "Fitzroya",
	"Peppermint": "Eucalyptus piperita",
	"Pignut Hickory": "Carya ovalis",
	"Pin Cherry": "Prunus",
	"Purple Magnolia": "Magnolia macrophylla",
	"Red Spruce": "Spruce",
	"Sassafras": "Ocotea odorifera",
	"Scotch Pine Reviews": "Pinus sylvestris",
	"Serviceberry": "Amelanchier asiatica",
	"Sour Cherry": "Cherry blossom",
	"Southern Live Oak": "Live oak",
	"Southern Magnolia": "Magnolia grandiflora (Brooklyn)",
	"Sweet Cherry": "Adansonia",
	"Sweetbay Magnolia": "Liquidambar styraciflua",
	"Tanoak": "Fagaceae",
	"Tulip": "Spathodea",
	"Turkey Oak": "Quercus suber",
	"White Ash": "Fraxinus americana",
	"White Oak": "Quercus alba",
	"White Spruce": "Picea glauca",
	"Yellow Birch": "Betula papyrifera",
};