const items = [
	{ text: 'Кузовной ремонт и покраска с подбором цвета для RAM 1500', img: require('../img/item1.webp') },
	{ text: 'Полировка кузова Ford Mustang + керамика, химчистка салона, окрас суппортов в Viva Magenta под кэнди-лаком', img: require('../img/item2.webp') },
	{ text: 'Кузовной ремонт, оклейка BMW X3 матовым полиуретаном, шумоизоляция дверей', img: require('../img/item3.webp') },
	{ text: 'Бережно переобули на зиму эксклюзивный Land Rover Defender Urban XRS 12/25! Фирменный шиномонтаж на стендах Hunter', img: require('../img/item4.webp') },
	{ text: 'Цветные ремни безопасности для Dodge Charger King Daytona: подобрали оттенок под цвет кузова по огромному каталогу и напечатали его!', img: require('../img/item5.webp') },
	{ text: 'Окрас крышки багажника с подбором цвета для Volkswagen Touareg, частичная оклейка полиуретаном, установка видеорегистратора и комплекс детейлинг-услуг', img: require('../img/item6.webp') },
	{ text: 'Забронировали Range Rover Sport глянцевым полиуретаном, почистили кожу и покрыли ее керамикой', img: require('../img/item7.webp') },
	{ text: 'Новая выхлопная система для RAM 1500', img: require('../img/item8.webp') },
	{ text: 'Кузовной ремонт для BMW M5 Competition: окрасили дверь с подбором цвета', img: require('../img/item9.webp') },
	{ text: 'Химчистка салона и керамика кожи для BMW X5', img: require('../img/item10.webp') },
	{ text: 'Детейлинг-услуги для Nissan Teana', img: require('../img/item11.webp') },
	{ text: 'Фирменный шиномонтаж с адаптацией и балансировкой на стендах Hunter для Audi RS4', img: require('../img/item12.webp') },
	{ text: '"Мы — Веном!" Ремни безопасности с антигероем комиксов Marvel отправили в город Обнинск', img: require('../img/item13.webp') },
	{ text: 'Полировка и керамика кузова Mercedes G63AMG, защита передней части и салона полиуретаном, антихром, цветные ремни безопасности, кованые диски и фирменный шиномонтаж на стендах Hunter', img: require('../img/item14.webp') },
	{ text: 'Оклеили BMW X7 матовым полиуретаном и защитили глянец в салоне', img: require('../img/item15.webp') },
	{ text: 'Техническое обслуживание, полировка + керамика кузова, химчистка салона, окрас дисков для невероятного Bentley Arnage!', img: require('../img/item16.webp') },
	{ text: 'Устраняем биение в руль и вибрации на клубном Mercedes GLE с помощью топового шиномонтажного оборудования Hunter!', img: require('../img/item17.webp') },
	{ text: 'Построили выхлопную систему с двумя режимами громкости для RAM 1500', img: require('../img/item18.webp') },
	{ text: 'Оклеили Mercedes GLA 45 AMG в винил от Oracal в оттенке Aquamarine, покрыли пленку керамикой. Окрасили суппорта в красный цвет с логотипами AMG', img: require('../img/item19.webp') },
	{ text: 'Техническое обслуживание Toyota Land Cruiser 200', img: require('../img/item20.webp') },
	{ text: 'Окрас вставок решетки радиатора и ручек Porsche Cayenne GTS в черный глянец. Окрас ключа в цвет кузова', img: require('../img/item21.webp') },
	{ text: 'Защитили прозрачным глянцевым полиуретаном RAM TRX', img: require('../img/item22.webp') },
	{ text: 'Ремни безопасности в стиле полицейских лент для Dodge Charger', img: require('../img/item23.webp') },
	{ text: 'Оклеили Volkswagen Multivan в сочетание матового и глянцевого полиуретанов! Выполнили химчистку салона', img: require('../img/item24.webp') },
	{ text: 'Плановое техническое обслуживание Porsche Macan', img: require('../img/item25.webp') },
	{ text: 'Полировка кузова Infiniti QX70 с покрытием керамикой, химчистка салона и мойка подкапотного пространства', img: require('../img/item26.webp') },
	{ text: 'Комплексная шумоизоляция салона, установка доводчиков дверей на лимитированный Mercedes G63 AMG Grand Edition! + Новые кованые диски и фирменный шиномонтаж на стендах Hunter', img: require('../img/item27.webp') },
	{ text: 'Оклеили в серый винил и матовый полиуретан RAM TRX! Окрас текстурного пластика, пневмосигнал Hadley, световая балка Rigid, комплексная шумоизоляция, зеркала с гравировкой', img: require('../img/item28.webp') },
	{ text: 'Техническое обслуживание Audi Q3 S-line', img: require('../img/item29.webp') },
	{ text: 'Оклеили Geely Atlas матовым полиуретаном', img: require('../img/item30.webp') },
];

export default items;
